apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remediation-worker-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gympt-apps

  source:
    repoURL: https://github.com/hj-3/gympt-gitops.git
    targetRevision: main
    path: charts/remediation-worker
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: "dev-latest"

  destination:
    server: https://kubernetes.default.svc
    namespace: workers

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
