apiVersion: v1
kind: ResourceQuota
metadata:
  name: no-workloads
  namespace: default
spec:
  hard:
    pods: "0"
    replicationcontrollers: "0"
    count/deployments.apps: "0"
    count/statefulsets.apps: "0"
