apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gympt-platform

  source:
    repoURL: https://github.com/hj-3/gympt-gitops.git
    targetRevision: main
    path: platform/external-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
