apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gympt-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gympt

  source:
    repoURL: https://github.com/hj-3/gympt-gitops.git
    targetRevision: main
    path: argocd/applications/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
