apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gympt-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gympt-platform

  source:
    repoURL: https://github.com/gympt/gympt-gitops.git
    targetRevision: main
    path: argocd/applications/platform

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
