apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8001
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "agent-service.selectorLabels" . | nindent 4 }}
